`asyncio.**gather**(***aws**, **return_exceptions**=False)` — функция позволяет группировать awaitable-объекты для их одновременного выполнения. Функция производит конкурентный запуск awaitable объектов, переданных в нее, как последовательность `*aws`, и собирает результаты их работы. Она полезна в ситуациях, когда мы хотим создать множество задач или корутин заранее и затем хотим выполнить их все сразу, ожидая их завершения перед продолжением работы.

- `***aws**`: Последовательность awaitable объектов, которые должны быть выполнены конкурентно(`*****` _- оператор распаковки последовательности_). Если какой-то объект в aws является корутиной, функция `asyncio.gather()` автоматически запланирует его как задачу.  
     
- `**return_exceptions=False**`: (_`False` — дефолтное значение_) Если любая из асинхронных операций запущенная через `asyncio.**gather()**`завершается с исключением, `asyncio.**gather()**` немедленно прекращает выполнение и поднимает первое пойманное исключение. Остальные асинхронные операции продолжают свое выполнение.  
    Такое поведение предпочтительно, когда важно, чтобы все операции были успешно выполнены и любое исключение является критическим сбоем, который требует немедленного внимания.  
     
- Когда `return_exceptions=**True**`: `asyncio.**gather()**` продолжает выполнение, даже если одна или несколько асинхронных операций завершаются с исключением. Вместо поднятия исключений они включаются в результирующий список вместе с успешно завершенными операциями.   
    Этот режим полезен, когда требуется обработать все результаты (_или исключения_) после выполнения всех операций, например, для логирования, анализа ошибок или чистки ресурсов. Этот режим позволяет агрегировать как успешные результаты, так и исключения для последующей обработки.
    

### Особенности  `asyncio.gather()`

**1. Конкурентное выполнение задач.** `asyncio.**gather()**` позволяет запускать несколько корутин или задач одновременно, что ускоряет выполнение программы и повышает ее производительность.

**2. `await asyncio.gather()` возвращает список из результатов задач в том же порядке, в каком они переданы в `asyncio.gather()`.**  Вне зависимости от времени выполнения переданных в **`asyncio.gather()`** задач, результаты будут сохранены в том порядке, в котором задачи передавались в функцию.

```python
import asyncio
import random

async def my_coroutine(name):
    delay = random.random()
    await asyncio.sleep(delay)
    return f"Корутина {name}: {round(delay, 2)}"

async def main():        
    results = await asyncio.gather(*[my_coroutine(i) for i in range(1, 6)])
    print(results)

asyncio.run(main())   
```

Вывод:

```css
['Корутина 1: 0.66', 'Корутина 2: 0.91', 'Корутина 3: 0.29', 'Корутина 4: 0.07', 'Корутина 5: 0.38']
```

Ваш вывод может отличаться, но важно помнить, что время выполнения задач не влияет на порядок вывода результатов.

**3. Гибкое управление исключениями.** **`asyncio.gather()`** позволяет управлять исключениями, возникающими в корутинах. С помощью параметра `return_exceptions` мы можем выбрать, нужно ли возвращать исключения в результате работы функции.

При использовании значения `return_exceptions=False` по умолчанию, любая ошибка возникшая в корутине будет проброшена в основной код. При этом важно помнить, что задачи, в которых не возникло исключение, не отменяются, а продолжают свое выполнение. 

В случае `return_exceptions=True` для тех корутин, которые завершились с ошибкой, в значение результата будет записана возникшая ошибка: